<table>
        <td>
        <td><img src="https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/logo_ECI.png" width="400"/></td>
        <td>&nbsp;</td>
        <td>
            <h1 style="font-size:200%;color:blue;text-align:center">    <FONT COLOR="blue"> DataFrames </p> Funciones en Python  </FONT>         </h1></td>         
        <td>
            <tp><p style="font-size:99%;text-align:center">Diplomado Ciencia de Datos </p></tp>
            <tp><p style="font-size:115%;text-align:center">2026-2</p></tp>
            <tp><p style="font-size:115%;text-align:center">Prof. Fabián Sánchez</p></tp>
        </td>
    </tr>
</table>

<FONT SIZE=5 COLOR="blue"> Contenidos del Notebook </FONT>

En este notebook encontrará:

- Funciones en Python

```python
def function(x):
  ....
  return ...
```

In [40]:
# importamos las librerías
import pandas as pd
import numpy as np

In [41]:
# cargamos los datos crédito
credito = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/credict_para_limpiar.csv")
credito.head()  # na_values("")

,Trajeta,Reportes Negativos,Edad,Ingreso,Proporcion de Gasto,Gasto,Propietario de Vivienda,Trabajor Independiente,Dependientes,Meses de Historial,Tarjetas Principales,Cuentas Activas
0,yes,0,37.66667,4.5200,0.033270,124.983300,yes,no,3,54,1,12.0
1,yes,0,33.25,2.4200,0.005217,9.854167,no,no,3,34,1,13.0
2,yes,0,33.66667,4.5000,0.004156,15.000000,yes,no,4,5o,1,5.0
3,yes,0,30.5,2.5400,0.065214,137.869200,no,no,0,25,1,7.0
4,yes,0,32.16667,9.7867,0.067051,546.503300,yes,no,2,64,1,5.0

In [46]:
hepatitis = pd.read_excel("https://github.com/Fabian830348/Bases_Datos/raw/master/hepatitis.xlsx")
hepatitis.head()

,Clase,Edad,Sexo,Esteroides,Antivirales,Fatiga,Malestar,Anorexia,Higado Grande,Cirrosis,Bazo palpable,Arañas,Ascites,Varices,Billirubina,Fosfato,SGOT,Albumina,Protina,Histologia
0,Vivo,30,Mujer,No,Sí,Sí,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,1.0,85,18,4.0,0,No
1,Vivo,50,Hombre,No,Sí,No,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,0.9,135,42,3.5,0,No
2,Vivo,78,Hombre,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,0.7,96,32,4.0,0,No
3,Vivo,31,Hombre,,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,0.7,46,52,4.0,80,No
4,Vivo,34,Hombre,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,1.0,0,200,4.0,0,No

In [60]:
homicidios = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/master/homicidios.csv")
homicidios.head()

,Fecha,Departamento,Municipio,Día,Hora,Barrio,Zona,Clase de sitio,Arma empleada,Móvil Agresor,Móvil Victima,Edad,Sexo,Estado civil,País de nacimiento,Clase de empleado,Profesión,Escolaridad,Código DANE,Cantidad
0,1/1/2017,AMAZONAS,LETICIA (CT),Domingo,15:05:00,KILOMETRO 11,RURAL,CARRETERA,ARMA BLANCA / CORTOPUNZANTE,PASAJERO MOTOCICLETA,PASAJERO MOTOCICLETA,20,MASCULINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,-,SECUNDARIA,"91,001,000",1
1,1/1/2017,ANTIOQUIA,BETANIA,Domingo,21:20:00,LA CUMBRE,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,21,MASCULINO,SOLTERO,COLOMBIA,INDEPENDIENTE,-,PRIMARIA,"5,091,000",1
2,1/1/2017,ANTIOQUIA,COPACABANA,Domingo,4:48:00,MACHADO,URBANA,DENTRO DE LA VIVIENDA,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,22,MASCULINO,UNION LIBRE,COLOMBIA,INDEPENDIENTE,-,SECUNDARIA,"5,212,000",1
3,1/1/2017,ANTIOQUIA,EBÉJICO,Domingo,5:00:00,SAGUA,RURAL,FINCAS Y SIMILARES,ARMA DE FUEGO,A PIE,A PIE,46,MASCULINO,SOLTERO,COLOMBIA,INDEPENDIENTE,-,SECUNDARIA,"5,240,000",1
4,1/1/2017,ANTIOQUIA,EL BAGRE,Domingo,6:30:00,LAS BRISAS,URBANA,VIAS PUBLICAS,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,37,MASCULINO,UNION LIBRE,COLOMBIA,INDEPENDIENTE,-,PRIMARIA,"5,250,000",1

# <FONT SIZE=5 COLOR="purple"> 1. Funciones en Python </FONT>

- Las funciones son bloques de código reutilizables que permiten organizar y estructurar programas de manera eficiente.

- Su principal objetivo es encapsular tareas específicas, facilitando la lectura, el mantenimiento y la reutilización del código.

- En Python, las funciones se definen mediante la palabra clave *def*
y pueden recibir parámetros de entrada, realizar operaciones y devolver resultados.

```python
def function(x,y,z..):
  .....
  return ...  
```
- El uso de funciones contribuye a reducir la duplicación de código, mejorar la modularidad de los programas y simplificar la resolución de problemas complejos mediante su división en tareas más pequeñas.

- Favorecen la claridad del código y permiten desarrollar aplicaciones más robustas y fáciles de depurar.

En esta sección se presentan los conceptos básicos relacionados con la definición, uso y aplicación de funciones en Python, así como algunos ejemplos prácticos.

**Ejemplo 1**

In [1]:
def duplicar_valor(x):
  return 2*x

In [3]:
duplicar_valor(16)

32

**Ejemplo 2**

In [4]:
# ejemplo básico de función sin parámetros
def saludo():
  print("Hola cómo están. Esto es un saludo")

In [8]:
saludo()

Hola cómo están. Esto es un saludo

**Ejemplo 3**

In [9]:
# ejemplo de función que suma 4
def suma_cuatro(x):
  return(x+4)

In [10]:
suma_cuatro(85)

89

**Ejemplo 4**

In [11]:
# podemos hacer operaciones con un DataFrame
def cabeza_datos(x):
  return(x.head())

In [ ]:
cabeza_datos()

**Ejemplo 5**

In [12]:
# ejemplo básico de función usando print
def saludo2(nombre):
  print("Hola" , nombre, "Cómo estás?")

In [13]:
saludo2("Fabian")

Hola Fabian Cómo estás?

**Ejemplo 6**

In [19]:
# podemos colocar varios argumentos
def saludo3(nombre, apellido):
  print("¿Hola", nombre, apellido, "Cómo estás?")

In [20]:
saludo3("Hugo", "Sanchez")

¿Hola Hugo Sanchez Cómo estás?

**Ejemplo 7**

Definir una función para la siguiente operación

$$f(x,y) = x^3y^2-xy+4$$

In [21]:
def funcion1(x,y):
  z = x**3*y**2-x*y+4
  return(z)

In [22]:
funcion1(10,3)

8974

## <FONT SIZE=4 COLOR="purple"> 1.1 Observación sobre print y return en una función </FONT>

In [24]:
def funcion2(x,y):
  z = x**2+y**2+1
  print(z)

In [23]:
def funcion3(x,y):
  z = x**2+y**2+1
  return(z)

In [25]:
funcion2(2,6)

41

In [26]:
funcion3(2,6)

41

Los resultados son los mismos. Entonces ¿cuál es la diferencia?

In [27]:
x = funcion2(2,6)
x+10

41

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [28]:
y = funcion3(2,6)
y+10

51

La diferencia principal es que `print()` muestra información en pantalla, mientras que `return` devuelve un valor para que pueda ser utilizado por el resto del programa.

Podemos pensar como una calculadora.

- **print**:

  - la calculadora muestra el resultado en la pantalla.
  - cuando se quiere mostrar únicamente la información

- **return**:

  - la calculadora te entrega el resultado para que puedas usarlo en otro cálculo.
  - cuando queremos un resultados para seguir trabajando con él.

## <FONT SIZE=4 COLOR="purple"> 1.2 Formas diferentes del `print()` </FONT>

Para imprimir variables dentro del `print()` hay varias alternativas

- **f-strings**

- **.format()**

### <FONT SIZE=4 COLOR="purple"> 1.2.1 Forma tradicional </FONT>

Colocar la variable dentro del `print()` pero afuera de las comillas

In [29]:
# primera forma
def saludo3(nombre):
  print("Hola", nombre, "espero que estés bien")

In [30]:
saludo3("Carolina")

Hola Carolina espero que estés bien

### <FONT SIZE=4 COLOR="purple"> 1.2.2 Método `f"{variable}"` </FONT>

Colocar la variable dentro de ls comillas y que Python no lo tome como cadena de texto.

In [36]:
# método f"{variable}"
def saludo4(nombre):
  print(f"Buenos días {nombre}, espero que estés bien")

In [37]:
saludo4("Ana María")

Buenos días Ana María, espero que estés bien

### <FONT SIZE=4 COLOR="purple"> 1.2.3 Método `"{}".format(variable)` </FONT>

También permite escribir la variable dentro de las comillas y que Python la identifique como variable y no cadena de texto.

In [38]:
def saludo5(nombre):
  print("Hola {}, me alegra mucho verte".format(nombre))

In [39]:
saludo5("Carlos")

Hola Carlos, me alegra mucho verte

**Ejercicio**

Generar funciones para:

- Calcular el área de un rectángulo
- Conversión de celsius a fahrenheit
- Generar un correo intitucional: nombre.apellido@universidad.edu.co
- Calcular el índice de masa corporal
- Calcular interés simple

In [ ]:
# área del rectángulo

In [ ]:
# conversión de celsius a Fahrenheit

In [ ]:
# Generar correo institucional

In [ ]:
# Indice de masa corporal

In [ ]:
# interés simple

Veamos algunos ejemplos con DataFrames.

**Ejemplo 1**

In [52]:
# funcion indique número de fila y de número de columnas
def shape_datos(datos):
  print(f"El número de filas es {datos.shape[0]}")
  print("El número de columnas es", datos.shape[1])

In [51]:
shape_datos(credito)

El número de filas es 1319
El número de columnas es 12

**Ejemplo 2**

In [53]:
def exploracion_rapida(datos):
  primeros = datos.head()
  ultimos = datos.tail()
  return primeros, ultimos

In [54]:
exploracion_rapida(credito)

(  Trajeta  Reportes Negativos      Edad  Ingreso  Proporcion de Gasto  \
 0     yes                   0  37.66667   4.5200             0.033270
 1     yes                   0     33.25   2.4200             0.005217
 2     yes                   0  33.66667   4.5000             0.004156
 3     yes                   0      30.5   2.5400             0.065214
 4     yes                   0  32.16667   9.7867             0.067051

         Gasto Propietario de Vivienda Trabajor Independiente  Dependientes  \
 0  124.983300                     yes                     no             3
 1    9.854167                      no                     no             3
 2   15.000000                     yes                     no             4
 3  137.869200                      no                     no             0
 4  546.503300                     yes                     no             2

   Meses de Historial  Tarjetas Principales  Cuentas Activas
 0                 54                     1             12.0
 1                 34                     1             13.0
 2                 5o                     1              5.0
 3                 25                     1              7.0
 4                 64                     1              5.0  ,
      Trajeta  Reportes Negativos      Edad  Ingreso  Proporcion de Gasto  \
 1314     yes                   0  33.58333    4.566             0.002146
 1315      no                   5  23.91667    3.192             0.000376
 1316     yes                   0  40.58333    4.600             0.026513
 1317     yes                   0  32.83333    3.700             0.008999
 1318     yes                   0     48.25    3.700             0.111619

            Gasto Propietario de Vivienda Trabajor Independiente  Dependientes  \
 1314    7.333333                     yes                     no             0
 1315    0.000000                      no                     no             3
 1316  101.298300                     yes                     no             2
 1317   26.996670                      no                    yes             0
 1318  344.157500                     yes                     no             2

      Meses de Historial  Tarjetas Principales  Cuentas Activas
 1314                 94                     1             19.0
 1315                 12                     1              5.0
 1316                  1                     1              2.0
 1317                 60                     1              7.0
 1318                  2                     1              0.0  )

Observe la forma en que se imprime

In [55]:
def exploracion_rapida(datos):
  primeros = datos.head()
  ultimos = datos.tail()
  return display(primeros), display(ultimos)

In [56]:
exploracion_rapida(credito)

,Trajeta,Reportes Negativos,Edad,Ingreso,Proporcion de Gasto,Gasto,Propietario de Vivienda,Trabajor Independiente,Dependientes,Meses de Historial,Tarjetas Principales,Cuentas Activas
0,yes,0,37.66667,4.5200,0.033270,124.983300,yes,no,3,54,1,12.0
1,yes,0,33.25,2.4200,0.005217,9.854167,no,no,3,34,1,13.0
2,yes,0,33.66667,4.5000,0.004156,15.000000,yes,no,4,5o,1,5.0
3,yes,0,30.5,2.5400,0.065214,137.869200,no,no,0,25,1,7.0
4,yes,0,32.16667,9.7867,0.067051,546.503300,yes,no,2,64,1,5.0

,Trajeta,Reportes Negativos,Edad,Ingreso,Proporcion de Gasto,Gasto,Propietario de Vivienda,Trabajor Independiente,Dependientes,Meses de Historial,Tarjetas Principales,Cuentas Activas
1314,yes,0,33.58333,4.566,0.002146,7.333333,yes,no,0,94,1,19.0
1315,no,5,23.91667,3.192,0.000376,0.000000,no,no,3,12,1,5.0
1316,yes,0,40.58333,4.600,0.026513,101.298300,yes,no,2,1,1,2.0
1317,yes,0,32.83333,3.700,0.008999,26.996670,no,yes,0,60,1,7.0
1318,yes,0,48.25,3.700,0.111619,344.157500,yes,no,2,2,1,0.0

(None, None)

**Ejemplo 3**

In [58]:
def exploracion(datos):
    print("Primeros 5 registros \n")
    display(datos.head())

    print("\n Últimos 5 registros \n")
    display(datos.tail())

    print("\n Tamaño de los datos \n")
    print(datos.shape)
    print(f"Filas: {datos.shape[0]}")
    print(f"Columnas: {datos.shape[1]}")

    print("\n Nombres de las columnas \n")
    print(datos.columns)

    print("\n Información de los datos \n")
    print(datos.info())

    print("\n Estadísticas descriptivas \n")
    display(datos.describe())

    print("\n Valores faltantes \n")
    display(datos.isna().sum())

In [59]:
exploracion(credito)

Primeros 5 registros

,Trajeta,Reportes Negativos,Edad,Ingreso,Proporcion de Gasto,Gasto,Propietario de Vivienda,Trabajor Independiente,Dependientes,Meses de Historial,Tarjetas Principales,Cuentas Activas
0,yes,0,37.66667,4.5200,0.033270,124.983300,yes,no,3,54,1,12.0
1,yes,0,33.25,2.4200,0.005217,9.854167,no,no,3,34,1,13.0
2,yes,0,33.66667,4.5000,0.004156,15.000000,yes,no,4,5o,1,5.0
3,yes,0,30.5,2.5400,0.065214,137.869200,no,no,0,25,1,7.0
4,yes,0,32.16667,9.7867,0.067051,546.503300,yes,no,2,64,1,5.0

 Últimos 5 registros

,Trajeta,Reportes Negativos,Edad,Ingreso,Proporcion de Gasto,Gasto,Propietario de Vivienda,Trabajor Independiente,Dependientes,Meses de Historial,Tarjetas Principales,Cuentas Activas
1314,yes,0,33.58333,4.566,0.002146,7.333333,yes,no,0,94,1,19.0
1315,no,5,23.91667,3.192,0.000376,0.000000,no,no,3,12,1,5.0
1316,yes,0,40.58333,4.600,0.026513,101.298300,yes,no,2,1,1,2.0
1317,yes,0,32.83333,3.700,0.008999,26.996670,no,yes,0,60,1,7.0
1318,yes,0,48.25,3.700,0.111619,344.157500,yes,no,2,2,1,0.0

 Tamaño de los datos

(1319, 12)
Filas: 1319
Columnas: 12

 Nombres de las columnas

Index(['Trajeta', 'Reportes Negativos', 'Edad', 'Ingreso',
       'Proporcion de Gasto', 'Gasto', 'Propietario de Vivienda',
       'Trabajor Independiente', 'Dependientes', 'Meses de Historial',
       'Tarjetas Principales', 'Cuentas Activas'],
      dtype='object')

 Información de los datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Trajeta                  1319 non-null   object
 1   Reportes Negativos       1319 non-null   int64
 2   Edad                     1317 non-null   object
 3   Ingreso                  1318 non-null   float64
 4   Proporcion de Gasto      1318 non-null   float64
 5   Gasto                    1319 non-null   float64
 6   Propietario de Vivienda  1318 non-null   object
 7   Trabajor Independiente   1317 non-null   object
 8   Dependientes             1319 non-null   int64
 9   Meses de Historial       1314 non-null   object
 10  Tarjetas Principales     1319 non-null   int64
 11  Cuentas Activas          1318 non-null   float64
dtypes: float64(4), int64(3), object(5)
memory usage: 123.8+ KB
None

 Estadísticas descriptivas

,Reportes Negativos,Ingreso,Proporcion de Gasto,Gasto,Dependientes,Tarjetas Principales,Cuentas Activas
count,1319.000000,1318.000000,1318.000000,1319.000000,1319.000000,1319.000000,1318.000000
mean,0.456406,3.360342,0.076440,185.057071,0.993935,0.817286,7.002276
std,1.345267,1.684647,0.186243,272.218917,1.247745,0.386579,6.305256
min,0.000000,0.210000,0.000109,0.000000,0.000000,0.000000,0.000000
25%,0.000000,2.240625,0.002409,4.583333,0.000000,1.000000,2.000000
50%,0.000000,2.900000,0.039175,101.298300,1.000000,1.000000,6.000000
75%,0.000000,4.000000,0.094029,249.035800,2.000000,1.000000,11.000000
max,14.000000,13.500000,3.890000,3099.505000,6.000000,1.000000,46.000000

 Valores faltantes

Trajeta                    0
Reportes Negativos         0
Edad                       2
Ingreso                    1
Proporcion de Gasto        1
Gasto                      0
Propietario de Vivienda    1
Trabajor Independiente     2
Dependientes               0
Meses de Historial         5
Tarjetas Principales       0
Cuentas Activas            1
dtype: int64

**Ejemplo 4**

In [61]:
def tipos(df):
    return pd.DataFrame({
        "Columna": df.columns,
        "Tipo": df.dtypes.values
    })

In [62]:
tipos(homicidios)

               Columna    Tipo
0                Fecha  object
1         Departamento  object
2            Municipio  object
3                  Día  object
4                 Hora  object
5               Barrio  object
6                 Zona  object
7       Clase de sitio  object
8        Arma empleada  object
9        Móvil Agresor  object
10       Móvil Victima  object
11                Edad   int64
12                Sexo  object
13        Estado civil  object
14  País de nacimiento  object
15   Clase de empleado  object
16           Profesión  object
17         Escolaridad  object
18         Código DANE  object
19            Cantidad   int64

**Ejemplo 5**

In [63]:
# forma 1 de escribir
def unicos(datos,variable):
  return datos[variable].unique()

In [64]:
unicos(credito,"Propietario de Vivienda")

array(['yes', 'no', nan, 'Yes', 'NO'], dtype=object)

In [65]:
# forma 2 de escribir
def valores_unicos(df, columna):
    return pd.DataFrame({
        "Valores únicos": df[columna].unique()
    })

In [66]:
valores_unicos(credito, "Trajeta")

  Valores únicos
0            yes
1             no
2            Yes
3             No

**Ejemplo 6**

In [69]:
# detectar todas las filas donde esta variable no tiene un valor numérico válido.
def problema_texto(datos, variable):
  u = pd.to_numeric(datos[variable], errors='coerce').isna()
  posiciones = np.where(u)[0]
  print(posiciones)
  return datos.iloc[posiciones]

In [70]:
problema_texto(credito,"Meses de Historial")

[  2  14  32 252 320 399 465 496]

,Trajeta,Reportes Negativos,Edad,Ingreso,Proporcion de Gasto,Gasto,Propietario de Vivienda,Trabajor Independiente,Dependientes,Meses de Historial,Tarjetas Principales,Cuentas Activas
2,yes,0,33.66667,4.500,0.004156,15.00000,yes,no,4,5o,1,5.0
14,yes,0,35.33333,1.908,0.026907,42.61500,yes,no,2,12o,0,5.0
32,no,1,24.91667,3.150,0.000381,0.00000,yes,no,1,4o,1,5.0
252,yes,0,25.08333,2.650,0.009651,20.47917,no,no,0,NaN,1,9.0
320,no,2,28.16667,2.600,0.000462,0.00000,yes,no,2,NaN,1,3.0
399,yes,0,22.58333,2.250,0.011111,20.08333,NaN,no,0,NaN,1,4.0
465,no,0,23.83333,2.200,0.000545,0.00000,no,no,0,NaN,0,0.0
496,yes,0,42.25,3.235,0.024766,66.26417,yes,no,2,NaN,1,3.0

**Ejemplo 7**

In [71]:
# ¿qué hace la siguiente función?
def fuera_rango(datos, variable, minimo, maximo):
    problema = (datos[variable] < minimo) | (datos[variable] > maximo)
    posiciones = np.where(problema)[0]
    print("Posiciones:", posiciones)
    return datos.iloc[posiciones]

In [77]:
fuera_rango(homicidios, "Edad", 10, 80)

Posiciones: [    8    53    59   126   134   208   289   372   381   426   477   655
  1031  1146  1347  1356  1703  2076  2194  2368  2389  2390  2474  2523
  2805  2882  3107  3243  3364  3428  3483  3558  3569  3585  3608  3609
  3633  3680  3820  3908  3991  4031  4655  4813  4912  5179  5210  5276
  5281  5305  5382  5568  5689  6049  6050  6203  6217  6218  6309  6390
  6574  6659  6661  6735  6790  6805  6820  7263  7293  7742  7910  8108
  8223  8587  8783  9073  9171  9235  9489  9819  9919  9933 10068 10100
 10190 10215 10524 10752 10835 10863 10917 11291 11434 11450 11551 11597
 11598 11609]

,Fecha,Departamento,Municipio,Día,Hora,Barrio,Zona,Clase de sitio,Arma empleada,Móvil Agresor,Móvil Victima,Edad,Sexo,Estado civil,País de nacimiento,Clase de empleado,Profesión,Escolaridad,Código DANE,Cantidad
8,1/1/2017,ANTIOQUIA,MEDELLÍN (CT),Domingo,22:10:00,LA PILARICA C-7,URBANA,CASAS DE HABITACION,CONTUNDENTES,A PIE,A PIE,4,MASCULINO,SOLTERO,COLOMBIA,DESEMPLEADO,-,ANALFABETA,"5,001,000",1
53,1/1/2017,GUAJIRA,DIBULLA,Domingo,4:00:00,EL BOSQUE,URBANA,PARQUES,CONTUNDENTES,A PIE,A PIE,7,MASCULINO,SOLTERO,-,DESEMPLEADO,-,ANALFABETA,"44,090,000",1
59,1/1/2017,MAGDALENA,SABANAS DE SAN ANGEL,Domingo,3:00:00,CORREGIMIENTO LAS MULAS,RURAL,CASAS DE HABITACION,CONTUNDENTES,A PIE,A PIE,0,MASCULINO,SOLTERO,COLOMBIA,DESEMPLEADO,-,ANALFABETA,"47,660,000",1
126,1/3/2017,ATLÁNTICO,BARRANQUILLA (CT),Martes,22:10:00,REBOLO,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,PASAJERO MOTOCICLETA,A PIE,8,MASCULINO,SOLTERO,COLOMBIA,ESTUDIANTE,-,PRIMARIA,"8,001,000",1
134,1/3/2017,CAUCA,PIAMONTE,Martes,11:00:00,VDA. LA LIBERTAD,RURAL,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,2,MASCULINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,-,ANALFABETA,"19,533,000",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11450,12/19/2017,ANTIOQUIA,MEDELLÍN (CT),Martes,8:30:00,VDA. LA URQUITA - PALMITAS,RURAL,FINCAS Y SIMILARES,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,83,MASCULINO,VIUDO,COLOMBIA,AGRICULTOR,-,ANALFABETA,"5,001,000",1
11551,12/22/2017,CALDAS,CHINCHINÁ,Viernes,9:15:00,SECTOR EL LAGO,RURAL,LAGUNAS,CONTUNDENTES,A PIE,A PIE,4,FEMENINO,SOLTERO,COLOMBIA,DESEMPLEADO,-,ANALFABETA,"17,174,000",1
11597,12/23/2017,CUNDINAMARCA,SIMIJACA,Sábado,7:15:00,VER. CENTRO,RURAL,FINCAS Y SIMILARES,CONTUNDENTES,A PIE,A PIE,81,FEMENINO,CASADO,COLOMBIA,AMA DE CASA,-,PRIMARIA,"25,745,000",1
11598,12/23/2017,CUNDINAMARCA,SIMIJACA,Sábado,7:15:00,VER. CENTRO,RURAL,FINCAS Y SIMILARES,CONTUNDENTES,A PIE,A PIE,86,MASCULINO,CASADO,COLOMBIA,AGRICULTOR,-,PRIMARIA,"25,745,000",1
11609,12/23/2017,PUTUMAYO,PUERTO GUZMÁN,Sábado,3:30:00,VDA. MAYOYOQUE,RURAL,FINCAS Y SIMILARES,SIN EMPLEO DE ARMAS,A PIE,A PIE,9,FEMENINO,SOLTERO,COLOMBIA,DESEMPLEADO,-,PRIMARIA,"86,571,000",1

In [82]:
def revisar_na(datos):
  resultado = pd.DataFrame({"cantidad_na": datos.isna().sum(),
                            "porcentaje_na": datos.isna().mean() * 100})
  return resultado