<table>
        <td>
        <td><img src="https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/logo_ECI.png" width="400"/></td>
        <td>&nbsp;</td>
        <td>
            <h1 style="font-size:200%;color:blue;text-align:center">    <FONT COLOR="blue"> DataFrames </p> Parte 3: .iloc y loc  </FONT>         </h1></td>         
        <td>
            <tp><p style="font-size:99%;text-align:center">Diplomado Ciencia de Datos </p></tp>
            <tp><p style="font-size:115%;text-align:center">2026-1</p></tp>
            <tp><p style="font-size:115%;text-align:center">Prof. Fabián Sánchez</p></tp>
        </td>
    </tr>
</table>

# <FONT SIZE=5 COLOR="red"> Contenidos del Notebook </FONT>

En este notebook encontrará:

- Selección de filas y columnas

  + *.iloc*
  + *.loc*

- La función *Replace*

Iniciaremos importando la librería *pandas*

In [117]:
# importamos las librerías
import pandas as pd
import numpy as np

In [ ]:
# cargamos los datos: apartamentos
aptos = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/master/apartamentos.csv")
aptos.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [ ]:
# cargamos los datos: hepatitis
hepatitis = pd.read_excel("https://raw.github.com/Fabian830348/Bases_Datos/master/hepatitis.xlsx")
hepatitis.head()

,Clase,Edad,Sexo,Esteroides,Antivirales,Fatiga,Malestar,Anorexia,Higado Grande,Cirrosis,Bazo palpable,Arañas,Ascites,Varices,Billirubina,Fosfato,SGOT,Albumina,Protina,Histologia
0,Vivo,30,Mujer,No,Sí,Sí,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,1.0,85,18,4.0,0,No
1,Vivo,50,Hombre,No,Sí,No,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,0.9,135,42,3.5,0,No
2,Vivo,78,Hombre,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,0.7,96,32,4.0,0,No
3,Vivo,31,Hombre,,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,0.7,46,52,4.0,80,No
4,Vivo,34,Hombre,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,1.0,0,200,4.0,0,No

Vamos a trabajar inicialmente con apartamentos

In [ ]:
# eliminamos la primera variable
aptos.drop(columns = ["Unnamed: 0"], inplace = True)

In [ ]:
aptos.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

# <FONT SIZE=5 COLOR="green"> 1. Acceder a los elementos del DataFrame </FONT>

Para acceder a los elementos, o a las filas o columnas del DataFrame podemos usar:

- ***iloc*** : para acceder por la posición
- ***loc.*** : para acceder por el nombre

Si usamos la primera instrucción

- ***df.iloc[i,j]*** : elemento de la fila i y columna j.

- ***df.iloc[i]*** : devuelve la fila i

- ***df.iloc[lista i , lista j]*** : devuelve un data.frame con las filas en lista i y columnas en columna j.

- ***df.iloc[:, j]*** : devuelve toda columna j.

Si usamos la instrucción **.loc**

- ***df.loc[nombre fila , nombre columna]***: es lo mismo anterior pero con los nombres.

- ***df[nombre columna]*** : devuelve las columnas en name columnas

- ***df.columna*** : otra forma para acceder a una columna que en el nombre no tenga espacios en blanco.


<br>
<center><img src="https://github.com/Fabian830348/cursos/blob/master/intro/DATAFRAME.png?raw=true" alt="centered image" width="600" height="350"></center> <center><figcaption> <FONT SIZE=1 COLOR="black"> Fuente: Elaboración propia  </FONT> <figcaption></center>

## <FONT SIZE=4 COLOR="magenta"> 1.1 Ejemplos con **.iloc** </FONT>


<center><img src="https://github.com/Fabian830348/cursos/blob/master/intro/iloc1.png?raw=true" alt="centered image" width="600" height="350"></center> <center><figcaption> <FONT SIZE=1 COLOR="black"> Fuente: Elaboración propia  </FONT> <figcaption></center>

In [ ]:
aptos.head(6)

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si
5,140.0,71.00,norte,3,3,2,no,si,0.120,31.145508,si

**Para seleccionar un elemento**

Elemento de la fila $i$ y columna $j$

$$datos.iloc[i,j]$$

In [ ]:
# para seleccionar un elemento de la fila i, columna j.
aptos.iloc[3,4]

np.int64(3)

In [ ]:
aptos.iloc[0, 9]

np.float64(14.923002)

**Para seleccionar una fila**

Para seleccionar la fila $i$

$$datos.iloc[i]$$

In [ ]:
# para seleccionar una fila, simplemente no especificamos la columna
aptos.iloc[3]

precio            123.0
mt2               61.85
ubicacion         norte
estrato               2
alcobas               3
banos                 2
balcon               si
parqueadero          si
administracion     0.13
avaluo             27.0
terminado            no
Name: 3, dtype: object

In [ ]:
# si quiero varias filas
aptos.iloc[[0,3,4]]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.05,14.923002,no
3,123.0,61.85,norte,2,3,2,si,si,0.13,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.00,39.567000,si

In [ ]:
# si quiero un rango de filas. La instrucción range(a,b): inicia en a y termina en b-1
aptos.iloc[range(2,8)]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si
5,140.0,71.00,norte,3,3,2,no,si,0.120,31.145508,si
6,145.0,54.83,norte,3,2,2,si,si,0.140,27.000000,si
7,160.0,69.00,norte,3,3,2,si,si,0.127,29.672435,si

**Para seleccionar una columna**

Para seleccionar la columna $j$

$$datos.iloc[:,j]$$

In [ ]:
aptos.iloc[:,2]

0         norte
1         norte
2         norte
3         norte
4         norte
         ...
689    laureles
690    laureles
691    laureles
692    laureles
693    laureles
Name: ubicacion, Length: 694, dtype: object

In [ ]:
# seleccionar varias columnas
aptos.iloc[:,[2,5,8]]

    ubicacion  banos  administracion
0       norte      1           0.050
1       norte      1           0.069
2       norte      2           0.000
3       norte      2           0.130
4       norte      2           0.000
..        ...    ...             ...
689  laureles      3           0.570
690  laureles      3           0.450
691  laureles      4           0.747
692  laureles      3           0.340
693  laureles      4           1.600

[694 rows x 3 columns]

**Varias columnas y varias filas**

<center><img src="https://github.com/Fabian830348/cursos/blob/master/intro/iloc2.png?raw=true" alt="centered image" width="450" height="350"></center> <center><figcaption> <FONT SIZE=1 COLOR="black"> Fuente: Elaboración propia  </FONT> <figcaption></center>

In [ ]:
# filas 1 y 3 y columnas 0 y 1
aptos.iloc[[1,3], [0,1]]

   precio    mt2
1    93.0  56.92
3   123.0  61.85

In [ ]:
# las primeras 100 filas
aptos.iloc[0:100]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si
...,...,...,...,...,...,...,...,...,...,...,...
95,220.0,94.00,poblado,6,3,2,no,si,0.250,107.858000,si
96,220.0,77.00,poblado,5,3,2,no,si,0.235,124.200000,si
97,225.0,78.40,poblado,6,1,2,si,si,0.250,137.438000,si
98,228.0,85.00,poblado,6,3,2,no,si,0.308,136.561000,no
99,230.0,96.00,poblado,6,3,2,no,si,0.308,131.000000,si

In [ ]:
# para seleccionar la segunda, tercera y primera fila
aptos.iloc[[1,2,0]]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no

In [ ]:
# la novena columna
aptos.iloc[: , 9 ]

0       14.923002
1       27.000000
2       15.738427
3       27.000000
4       39.567000
          ...
689    233.784000
690    258.850000
691    326.157000
692    324.114000
693    320.000000
Name: avaluo, Length: 694, dtype: float64

In [ ]:
# para seleccionar de la columna 3 en adelante
aptos.iloc[: , 3:]

,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,3,3,1,si,si,0.050,14.923002,no
1,2,2,1,si,si,0.069,27.000000,si
2,3,2,2,no,no,0.000,15.738427,no
3,2,3,2,si,si,0.130,27.000000,no
4,4,3,2,si,no,0.000,39.567000,si
...,...,...,...,...,...,...,...,...
689,5,4,3,si,si,0.570,233.784000,si
690,6,4,3,si,si,0.450,258.850000,si
691,6,3,4,no,si,0.747,326.157000,si
692,5,3,3,si,si,0.340,324.114000,si
693,5,3,4,si,si,1.600,320.000000,si

## <FONT SIZE=4 COLOR="magenta"> 1.2 Ejemplos con **.loc** </FONT>

Veamos algunos ejemplos con **.loc**.

Recordemos que en *.iloc* se busca por posición y en *.loc* por nombre.

In [ ]:
aptos.columns

Index(['precio', 'mt2', 'ubicacion', 'estrato', 'alcobas', 'banos', 'balcon',
       'parqueadero', 'administracion', 'avaluo', 'terminado'],
      dtype='object')

In [ ]:
# verificar el nombre de los índices
aptos.index

RangeIndex(start=0, stop=694, step=1)

In [ ]:
aptos.loc[ 5 , "avaluo"]

np.float64(31.145508)

In [ ]:
# la columna ubicacion
aptos.loc[:,"ubicacion"]

0         norte
1         norte
2         norte
3         norte
4         norte
         ...
689    laureles
690    laureles
691    laureles
692    laureles
693    laureles
Name: ubicacion, Length: 694, dtype: object

In [ ]:
# seleccionar la fila 5
aptos.loc[5]

precio                140.0
mt2                    71.0
ubicacion             norte
estrato                   3
alcobas                   3
banos                     2
balcon                   no
parqueadero              si
administracion         0.12
avaluo            31.145508
terminado                si
Name: 5, dtype: object

In [ ]:
aptos.loc[: , "estrato": ]

,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,3,3,1,si,si,0.050,14.923002,no
1,2,2,1,si,si,0.069,27.000000,si
2,3,2,2,no,no,0.000,15.738427,no
3,2,3,2,si,si,0.130,27.000000,no
4,4,3,2,si,no,0.000,39.567000,si
...,...,...,...,...,...,...,...,...
689,5,4,3,si,si,0.570,233.784000,si
690,6,4,3,si,si,0.450,258.850000,si
691,6,3,4,no,si,0.747,326.157000,si
692,5,3,3,si,si,0.340,324.114000,si
693,5,3,4,si,si,1.600,320.000000,si

In [ ]:
# seleccionar las columnas precio, mt2 y avaluo y las filas 2,5,6,7
aptos.loc[[2,5,6,7] , ["precio", "mt2", "avaluo"]]

   precio    mt2     avaluo
2   100.0  66.40  15.738427
5   140.0  71.00  31.145508
6   145.0  54.83  27.000000
7   160.0  69.00  29.672435

In [ ]:
# otro ejemplo
aptos.loc[ [10,20,0,7] , ["ubicacion","parqueadero"]]

    ubicacion parqueadero
10  occidente          no
20  occidente          si
0       norte          si
7       norte          si

# <FONT SIZE=5 COLOR="green"> 2. La función Replace </FONT>

Podemos cambiar elementos de las columnas con la función replace

$$datos[``Variable"] = datos[``Variable"].replace(\{Valor\_actual : Valor\_nuevo\})$$

Veamos un ejemplo

In [ ]:
aptos.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

In [ ]:
# cambiar el 79 93 100 por hola, muuu y chau en la primera columna
aptos2 = aptos.copy()
aptos2["precio"] = aptos2["precio"].replace({79 : "hola" , 93: "muuu" , 100 : "chau"})

In [ ]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,hola,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,muuu,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,chau,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si

# <FONT SIZE=5 COLOR="green"> 3. Revisar donde hay cierto elemento </FONT>

Supongamos que queremos saber las posiciones donde el precio es de 120 millones.

Para saber una determinada posición usamos la instrucción

$$np.where(condicion)$$

In [ ]:
# cuántos apartamentos tienen precio de 120 millones
sum(aptos["precio"] == 120)

8

In [ ]:
# saber las posiciones donde el precio es de 120 millones
np.where(aptos["precio"] == 120)

(array([ 27, 362, 363, 364, 365, 366, 528, 529]),)

Podemos ver la información de estos apartamentos

In [ ]:
aptos.iloc[[27, 362, 363, 364, 365, 366, 528, 529]]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
27,120.0,57.0,occidente,3,2,2,no,no,0.000,68.302000,si
362,120.0,60.0,aburra sur,3,3,2,si,no,0.000,121.000000,si
363,120.0,58.0,aburra sur,3,3,2,no,si,0.125,52.633209,si
364,120.0,60.0,aburra sur,3,2,2,si,no,0.000,44.469049,si
365,120.0,80.0,aburra sur,3,2,1,si,no,0.000,31.083971,si
366,120.0,60.0,aburra sur,3,3,1,no,no,0.092,28.684288,si
528,120.0,58.0,belen guayabal,3,3,2,no,si,0.067,90.000000,si
529,120.0,117.0,belen guayabal,3,4,1,si,no,0.000,61.099000,no

In [ ]:
aptos[aptos.precio == 120]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
27,120.0,57.0,occidente,3,2,2,no,no,0.000,68.302000,si
362,120.0,60.0,aburra sur,3,3,2,si,no,0.000,121.000000,si
363,120.0,58.0,aburra sur,3,3,2,no,si,0.125,52.633209,si
364,120.0,60.0,aburra sur,3,2,2,si,no,0.000,44.469049,si
365,120.0,80.0,aburra sur,3,2,1,si,no,0.000,31.083971,si
366,120.0,60.0,aburra sur,3,3,1,no,no,0.092,28.684288,si
528,120.0,58.0,belen guayabal,3,3,2,no,si,0.067,90.000000,si
529,120.0,117.0,belen guayabal,3,4,1,si,no,0.000,61.099000,no

# <FONT SIZE=5 COLOR="green"> 4. Ejemplo importante </FONT>

In [123]:
# cargamos los datos crédito
credito = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/credit_dip.csv")
credito.head()

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
0,yes,0,37.66667,4.5200,0.033270,124.983300,yes,no,3,54,1,12
1,yes,0,33.25,2.4200,0.005217,9.854167,no,no,3,34,1,13
2,yes,0,33.66667,4.5000,0.004156,15.000000,yes,no,4,5o,1,5
3,yes,0,30.5,2.5400,0.065214,137.869200,no,no,0,25,1,7
4,yes,0,32.16667,9.7867,0.067051,546.503300,yes,no,2,64,1,5

In [125]:
# información de los datos
credito.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   card         1319 non-null   object
 1   reports      1319 non-null   int64
 2   age          1319 non-null   object
 3   income       1319 non-null   float64
 4   share        1319 non-null   float64
 5   expenditure  1319 non-null   float64
 6   owner        1319 non-null   object
 7   selfemp      1319 non-null   object
 8   dependents   1319 non-null   int64
 9   months       1319 non-null   object
 10  majorcards   1319 non-null   int64
 11  active       1319 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 123.8+ KB

In [126]:
# revisar cadenas de texto en age
credito["age"].unique()

array(['37.66667', '33.25', '33.66667', '30.5', '32.16667', '23.25',
       '27.91667', '29.16667', '37.0', '28.41667', ' ', '30.0',
       '28.83333', '35.33333', '40.08333', '29.5', '39.5', '45.75',
       '35.25', '25.16667', '34.25', '35.75', '42.66667', '30.25',
       '21.66667', '22.25', '40.0', '21.83333', '29.41667', '24.91667',
       '21.0', '23.83333', '42.83333', '42.58333', '36.58333', '26.75',
       '27.75', '26.25', '23.33333', '29.91667', '38.33333', '28.16667',
       '35.58333', '37.75', '26.08333', '49.75', '24.25', '20.66667',
       '23.75', '25.75', '32.91667', '34.33333', '44.66667', '21.16667',
       '25.08333', '27.16667', '26.41667', '22.0', '27.33333', '26.16667',
       '40.75', '42.08333', '24.66667', '30.75', '27.41667', '33.0',
       '37.33333', '26.58333', '24.33333', '25.25', '0.5', '32.83333',
       '32.75', '54.583330000000004', '19.58333', '29.33333', '40.16667',
       '41.25', '34.5', '23.66667', '53.666669999999996', '34.0',
       '44.91667', '43.41667', '35.16667', '35.83333', '32.66667',
       '25.41667', '46.0', '35.0', '20.91667', '31.25', '23.16667',
       '23.0', '24.83333', '40.91667', '43.66667', '23.08333', '41.91667',
       '45.58333', '25.91667', '21.25', '23.41667', '22.16667',
       '40.83333', '18.66667', '20.08333', '24.75', '31.08333',
       '53.333330000000004', '20.58333', '18.41667', '21.41667', '42.0',
       '36.41667', '41.5', '26.5', '33.16667', '43.08333', '30.33333',
       '35.66667', '44.5', '43.25', '50.0', '31.75', '49.66667',
       '28.33333', '71.83334', '24.5', '30.08333', '32.58333', '48.91667',
       '25.33333', '28.58333', '32.33333', '23.58333', '30.83333',
       '34.66667', '31.5', '36.16667', '32.41667', '28.08333', '41.58333',
       '21.75', '43.5', '29.58333', '33.75', '24.16667', '24.08333',
       '32.0', '46.16667', '21.91667', '36.25', '49.41667', '47.58333',
       '21.58333', '30.41667', '62.916669999999996', '30.66667', '47.75',
       '39.75', '53.166669999999996', '22.83333', '61.083330000000004',
       '42.75', '27.58333', '22.5', '25.83333', '56.916669999999996',
       '30.16667', '34.58333', '31.33333', '27.83333', '46.25', '20.5',
       '28.0', '51.66667', '41.83333', '51.75', '53.5', '20.33333',
       '83.5', '26.91667', '65.91666', '35.91667', '24.58333', '43.83333',
       '46.91667', '57.666669999999996', '25.66667', '34.83333', '37.5',
       '40.33333', '24.41667', '41.16667', '29.83333', '42.91667',
       '34.16667', '63.5', '22.33333', '22.91667', '26.83333', '41.08333',
       '53.583330000000004', '20.75', '38.58333', '22.41667', '31.0',
       '29.08333', '38.0', '37.58333', '23.91667', '26.33333',
       '0.1666667', '44.58333', '27.66667', '45.0', '31.66667',
       '34.41667', '20.41667', '32.08333', '26.0', '36.91667', '22.66667',
       '28.25', '49.16667', '36.0', '29.25', '61.0', '54.416669999999996',
       '27.08333', '39.0', '47.08333', '33.08333', '45.66667', '39.66667',
       '27.25', '41.66667', '46.5', '21.08333', '22.58333', '25.58333',
       '38.25', '34.75', '28.75', '22.08333', '36.5', '53.0', '31.16667',
       '54.083330000000004', '45.83333', '20.83333', '48.33333',
       '63.166669999999996', '28.91667', '0.5833333', '20.16667', '25.0',
       '19.66667', '51.58333', '54.75', '45.08333', '54.5', '34.08333',
       '33.91667', '0.75', '51.25', '29.0', '33.5', '38.75', '43.33333',
       '62.0', '35.5', '21.5', '39.58333', '40.5', '47.16667', '45.5',
       '37.08333', '51.83333', '39.91667', '42.25', '27.5', '31.83333',
       '28.66667', '50.33333', '30.58333', '38.83333', '37.41667',
       '38.41667', '46.75', '52.25', '37.16667', '19.0', '36.83333',
       '45.41667', '39.33333', '47.83333', '47.5', '38.91667', '26.66667',
       '52.41667', '20.25', '22.75', '46.33333', '19.41667', '44.83333',
       '27.0', '39.16667', '31.41667', '40.41667', '43.58333', '40.58333',
       '42.16667', '47.33333', '38.5', '47.91667', '36.75', '23.5',
       '39.08333', '39.25', '47.41667', '49.58333', '49.83333', '37.25',
       '24.0', '57.083330000000004', '38.66667', '29.75', '30.91667',
       '60.083330000000004', '66.5', '74.16666', '55.166669999999996',
       '37.83333', '51.91667', '38.16667', '33.83333', '64.58334',
       '41.41667', '32.25', '28.5', '56.75', '39.41667', '31.91667',
       '35.08333', '57.333330000000004', '52.16667', '38.08333',
       '55.083330000000004', '19.83333', '34.91667', '18.75',
       '54.833330000000004', '62.5', '36.33333', '50.91667', '45.25',
       '36.08333', '25.5', '32.5', '47.0', '36.66667', '46.41667', '20.0',
       '52.33333', '59.0', '31.58333', '45.16667', '39.83333', '48.25',
       '48.75', '44.33333', '44.25', '18.16667', '19.91667', '18.5',
       '57.583330000000004', '58.916669999999996', '80.16666', '49.0',
       '44.0', '43.16667', '19.5', '61.583330000000004',
       '52.666669999999996', '40.66667', '61.166669999999996', '44.08333',
       '45.91667', '33.58333', '55.333330000000004', '19.08333',
       '51.33333', '41.0', '41.75', '63.75', '42.41667', '56.0',
       '19.16667', '67.16666', '57.75', '63.416669999999996', '48.16667',
       '43.91667', '33.33333', '60.25', '69.75', '53.25', '54.25',
       '43.75', '54.666669999999996', '55.25', '55.583330000000004',
       '52.75', '41.33333', '48.66667', '35.41667', '58.083330000000004'],
      dtype=object)

In [127]:
pd.to_numeric(credito.age, errors='coerce').isna()

0       False
1       False
2       False
3       False
4       False
        ...
1314    False
1315    False
1316    False
1317    False
1318    False
Name: age, Length: 1319, dtype: bool

In [128]:
np.where(pd.to_numeric(credito.age, errors='coerce').isna())

(array([11, 15]),)

In [129]:
credito.age[[11,15]]

11
15
Name: age, dtype: object

In [ ]:
# vamos a hacer coherción de datos: forzar a que se convierta en uno u otro tipo
credito.age= pd.to_numeric(credito.age, errors='coerce')

**veamos otra variable**

In [130]:
credito.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   card         1319 non-null   object
 1   reports      1319 non-null   int64
 2   age          1319 non-null   object
 3   income       1319 non-null   float64
 4   share        1319 non-null   float64
 5   expenditure  1319 non-null   float64
 6   owner        1319 non-null   object
 7   selfemp      1319 non-null   object
 8   dependents   1319 non-null   int64
 9   months       1319 non-null   object
 10  majorcards   1319 non-null   int64
 11  active       1319 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 123.8+ KB

In [131]:
# revisar cadenas de texto en months
credito["months"].unique()

array(['54', '34', '5o', '25', '64', '7', '77', '97', '65', '24', '36',
       '42', '26', '12o', '168', '96', '60', '28', '115', '12', '18',
       '13', '38', '74', '9', '14', '4o', '108', '46', '2', '8', '156',
       '98', '30', '0', '6', '48', '216', '33', '20', '3', '16', '182',
       '78', '4', '53', '144', '5', '94', '37', '15', '177', '172', '288',
       '87', '69', '161', '72', '1', '51', '120', '126', '27', '32', '52',
       '114', '180', '41', '67', '62', '84', '264', '164', '55', '57',
       '50', '11', '10', '17', '61', '128', '56', '45', '19', '252', '23',
       '35', '43', '300', '31', '76', '121', '21', '230', '204', '179',
       '40', '80', '59', '93', '49', '22', '408', '44', '63', '372',
       '113', '106', '90', '540', '188', '146', '301', '192', '150', '85',
       '133', '131', '270', '102', '151', '70', '125', '159', '101', '75',
       '117', '132', '158', '200', '210', '250', '109', '240', '268',
       '162', '135', '66', '110', '134', '160', '122', '86', '95', '186',
       '68', '138', '88', '244', '511', '29', '104', '47', '241', '147',
       '39', '236', '228', '136', '91', '100', '347', '82', '194', '243',
       '222', '365', '207', '209', '234', '58', '166', '99', '229', '269',
       '124', '303', '218', '118', '201', '220', '148', '143', '169',
       '242', '233', '105', '232', '528', '81', '429', '153', '276',
       '154', '111', '123'], dtype=object)

In [135]:
pd.to_numeric(credito.months, errors='coerce').isna()

0       False
1       False
2        True
3       False
4       False
        ...
1314    False
1315    False
1316    False
1317    False
1318    False
Name: months, Length: 1319, dtype: bool

In [136]:
sum(pd.to_numeric(credito.months, errors='coerce').isna())

3

In [147]:
np.where(pd.to_numeric(credito.months, errors='coerce').isna())[0]

array([ 2, 14, 32])

In [149]:
credito.iloc[list(np.where(pd.to_numeric(credito.months, errors='coerce').isna())[0])]

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
2,yes,0,33.66667,4.500,0.004156,15.000,yes,no,4,5o,1,5
14,yes,0,35.33333,1.908,0.026907,42.615,yes,no,2,12o,0,5
32,no,1,24.91667,3.150,0.000381,0.000,yes,no,1,4o,1,5

**Para pensar un poco**

In [158]:
# función para detectar
def problema_texto(datos, x):
  u = np.where(pd.to_numeric(credito.months, errors='coerce').isna())
  print(u)
  v = credito.iloc[list(np.where(pd.to_numeric(datos[x], errors='coerce').isna())[0])]
  return v

In [160]:
problema_texto(credito, "age")

(array([ 2, 14, 32]),)

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
11,no,0,,1.98,0.000606,0.000,yes,no,2,36,1,0
15,yes,0,,3.20,0.125819,335.435,yes,no,1,168,1,22